block_definitions:
    title:
        view_types:
            boat_blue:
                name: 'Schiff in Blau'
            boat_brown:
                name: 'Schiff in Braun'
            title_centered:
                name: 'Title centered'
            section:
                name: 'Title (section)'
            section_centered:
                name: 'Title (section centered)'

    button:
        view_types:
            button_lightblue:
                name: 'Button Hellblau'
            button_blue:
                name: 'Button Blau'
            button_green:
                name: 'Button Grün'

    list:
        view_types:
            list:
                item_view_types: &list_item_view_types
                    standard_with_intro:
                        name: 'Standard (with intro)'
                    overlay:
                        name: 'Overlay'
                    line:
                        name: 'Line - Bild rechts'
                    line_il:
                        name: 'Line - Bild links'
                    line_x:
                        name: 'Line - Bild abwechselnd'
                    line_h:
                        name: 'Line - Halb / Halb - Bild rechts'
                    line_h_il:
                        name: 'Line - Halb / Halb - Bild links'
                    line_h_x:
                        name: 'Line - Halb / Halb - Bild abwechselnd'

                    line_50_50_il:
                        name: '50 / 50 - Bild links'
                    line_50_50_ir:
                        name: '50 / 50 - Bild rechts'
                    line_50_50_x:
                        name: '50 / 50 - Bild/Text abwechselnd'
                    line_30_70_il:
                        name: '30 / 70 - Bild links'
                    line_30_70_ir:
                        name: '30 / 70 - Bild rechts'
                    line_30_70_x:
                        name: '30 / 70 - Bild/Text abwechselnd'

                    line_full_il:
                        name: 'Artikelvorschau - Bild links'

                    40_60_img_left_plus_list:
                        name: 'Bild links plus Zusatzliste'

            list_numbered:
                name: 'List (numbered)'
                item_view_types: *list_item_view_types
                valid_parameters: ['!number_of_columns']

            grid:
                item_view_types:
                    standard_with_intro:
                        name: 'Standard (with intro)'
                    teaser_bg_matrix:
                        name: 'Teaser Bild unten - Matrix'
                    teaser_bg_white:
                        name: 'Teaser Bild unten - weiß'
                    overlay:
                        name: 'Overlay'
                    event:
                        name: 'Veranstaltung'
                    button:
                        name: 'Knopf'
                valid_parameters: ['!children_submenu']

            grid_featured:
                name: 'Grid (featured)'
                item_view_types:
                    standard:
                        enabled: false
                    overlay:
                        name: 'Overlay'
                valid_parameters: ['!children_submenu']

            grid_tiles:
                name: 'Grid (Tiles)'
                item_view_types:
                    standard:
                        enabled: false
                    tile:
                        name: 'Tile'
                valid_parameters: ['!children_submenu']

    gallery:
        view_types:
            slider:
                item_view_types:
                    standard:
                        enabled: false
                    slide:
                        name: 'Slide'
            carousel:
                item_view_types:
                    standard:
                        enabled: false
                    carousel:
                        name: 'Carousel'
            thumb_gallery:
                item_view_types:
                    standard:
                        enabled: false
                    gallery_thumb:
                        name: 'Gallery thumb'
            grid_gallery:
                item_view_types:
                    standard:
                        enabled: false
                    gallery_grid:
                        name: 'Gallery grid'
            sushi_bar:
                item_view_types:
                    standard_with_intro:
                        name: 'Standard (with intro)'
                    overlay:
                        name: 'Overlay'
                    line:
                        name: 'Line'
