parameters:
    netgen_layouts.standard.block.block_definition_handler.list.children_submenu:
        none: block.list.children_submenu.none
        list: block.list.children_submenu.list
        tags: block.list.children_submenu.tags
        list_icons: block.list.children_submenu.list_icons

    netgen_layouts.standard.block.block_definition_handler.list.show_parent_informations:
        no: block.list.show_parent_informations.no
        title: block.list.show_parent_informations.title
        intro: block.list.show_parent_informations.intro
        title_intro: block.list.show_parent_informations.title_intro

services:
    netgen_layouts.standard.block.block_definition_handler.list:
        class: AppBundle\Block\BlockDefinition\Handler\ListExtendedHandler
        arguments:
            - "%netgen_layouts.standard.block.block_definition_handler.list.columns%"
            - "%netgen_layouts.standard.block.block_definition_handler.list.children_submenu%"
            - "%netgen_layouts.standard.block.block_definition_handler.list.show_parent_informations%"
        tags:
            - { name: netgen_layouts.block_definition_handler, identifier: list }
